'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EvoHtmlToPdfWebDemo

    Partial Public Class AppendExternalPDFs

        '''<summary>
        '''ctrlDemoLinksBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlDemoLinksBox As Global.EvoHtmlToPdfWebDemo.DemoLinksBox

        '''<summary>
        '''textBoxWebPageURL1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxWebPageURL1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''urlRequired1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents urlRequired1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''textBoxWebPageURL2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxWebPageURL2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''urlRequired2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents urlRequired2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''textBoxWebPageURL3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxWebPageURL3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''urlRequired3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents urlRequired3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblConvertMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConvertMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnConvert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConvert As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
