'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EvoHtmlToPdfWebDemo

    Partial Public Class HtmlToPdfElementDemo

        '''<summary>
        '''ctrlDemoLinksBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlDemoLinksBox As Global.EvoHtmlToPdfWebDemo.DemoLinksBox

        '''<summary>
        '''radioConvertURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radioConvertURL As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''radioConvertHTML control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radioConvertHTML As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''pnlConvertURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlConvertURL As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''textBoxWebPageURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxWebPageURL As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''urlRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents urlRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''pnlConvertHTML control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlConvertHTML As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''textBoxHTMLCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxHTMLCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RequiredFieldValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''textBoxBaseURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxBaseURL As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''radioConvertToSelectablePDF control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radioConvertToSelectablePDF As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''radioConvertToEmbeddedImagePDF control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radioConvertToEmbeddedImagePDF As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''textBoxXLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxXLocation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textBoxYLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxYLocation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textBoxWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textBoxHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cbFitWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbFitWidth As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbLiveLinks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbLiveLinks As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbEmbedFonts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbEmbedFonts As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbClientScripts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbClientScripts As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbBookmarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbBookmarks As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbJpegCompression control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbJpegCompression As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbAddHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbAddHeader As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbAddFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbAddFooter As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbAdditionalContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbAdditionalContent As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblConvertMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConvertMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnConvert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConvert As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
