'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EvoHtmlToPdfWebDemo

    Partial Public Class HtmlToPdfFeaturesDemo

        '''<summary>
        '''ctrlDemoLinksBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlDemoLinksBox As Global.EvoHtmlToPdfWebDemo.DemoLinksBox

        '''<summary>
        '''textBoxWebPageURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxWebPageURL As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''urlRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents urlRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''radioConvertToPdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radioConvertToPdf As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''radioConvertToImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radioConvertToImage As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''htmlConvertControlPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents htmlConvertControlPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cbLiveLinksEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbLiveLinksEnabled As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbBookmarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbBookmarks As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbFitWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbFitWidth As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbScriptsEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbScriptsEnabled As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbEmbedFonts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbEmbedFonts As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbJpegCompression control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbJpegCompression As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lnkBtnSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkBtnSettings As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlRenderMoreOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRenderMoreOptions As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlRenderCommonOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRenderCommonOptions As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''textBoxHtmlViewerWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxHtmlViewerWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvHtmlViewerWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvHtmlViewerWidth As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''textBoxHtmlViewerHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxHtmlViewerHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvHtmlViewerHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvHtmlViewerHeight As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''textBoxAuthUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxAuthUsername As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textBoxAuthPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxAuthPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textBoxConversionDelay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxConversionDelay As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvConversionDelay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvConversionDelay As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''textBoxNavigationTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxNavigationTimeout As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvNavigationTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvNavigationTimeout As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''pnlImageRenderOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlImageRenderOptions As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlImageFormat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlImageFormat As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlPDFRenderOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPDFRenderOptions As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlPDFPageFormat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPDFPageFormat As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlCompressionLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCompressionLevel As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlPageOrientation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPageOrientation As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlPdfSubset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPdfSubset As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cbShowheader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbShowheader As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbShowFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbShowFooter As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlPDFHeaderOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPDFHeaderOptions As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''textBoxHeaderHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxHeaderHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvHeaderHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvHeaderHeight As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''ddlHeaderLineColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHeaderLineColor As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cbDrawHeaderLine control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbDrawHeaderLine As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbShowHeaderOnFirstPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbShowHeaderOnFirstPage As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbShowHeaderOnOddPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbShowHeaderOnOddPages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbShowHeaderOnEvenPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbShowHeaderOnEvenPages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlPDFFooterOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPDFFooterOptions As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''textBoxFooterHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxFooterHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvFooterHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvFooterHeight As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''ddlFooterLineColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFooterLineColor As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cbDrawFooterLine control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbDrawFooterLine As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbShowFooterOnFirstPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbShowFooterOnFirstPage As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbShowFooterOnOddPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbShowFooterOnOddPages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbShowFooterOnEvenPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbShowFooterOnEvenPages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''textBoxLeftMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxLeftMargin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvLeftMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvLeftMargin As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''textBoxRightMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxRightMargin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvRightMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvRightMargin As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''textBoxTopMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxTopMargin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvTopMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTopMargin As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''textBoxBottomMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxBottomMargin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvBottomMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvBottomMargin As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''cbAvoidImageBreak control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbAvoidImageBreak As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblConvertMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConvertMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnConvert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConvert As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
