'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace EvoHtmlToPdfWebDemo

    '''<summary>
    '''HtmlInHeaderAndFooter class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class HtmlInHeaderAndFooter

        '''<summary>
        '''ctrlDemoLinksBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlDemoLinksBox As Global.EvoHtmlToPdfWebDemo.DemoLinksBox

        '''<summary>
        '''textBoxWebPageURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textBoxWebPageURL As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''urlRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents urlRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblConvertMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConvertMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnConvert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConvert As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''cbAlternateHeaderAndFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbAlternateHeaderAndFooter As Global.System.Web.UI.WebControls.CheckBox
    End Class
End Namespace
