'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EvoHtmlToPdfWebDemo


	''' <summary>
	''' InvoiceTemplate class.
	''' </summary>
	''' <remarks>
	''' Auto-generated class.
	''' </remarks>
	Partial Public Class InvoiceTemplate

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' litCustomerName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected litCustomerName As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' litCustomerAddress1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected litCustomerAddress1 As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' litCustomerAddress2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected litCustomerAddress2 As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' litCustomerPhone control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected litCustomerPhone As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' litCustomerEmail control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected litCustomerEmail As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' litInvoiceDate control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected litInvoiceDate As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' litInvoiceNum control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected litInvoiceNum As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' itemsGrid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected itemsGrid As Global.System.Web.UI.WebControls.GridView

		''' <summary>
		''' lblTotal control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblTotal As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' lblTotalPrice control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblTotalPrice As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
