'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EvoHtmlToPdfWebDemo

    Partial Public Class DemoLinksBox

        '''<summary>
        '''lnkGettingStarted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkGettingStarted As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkFeaturesDemo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkFeaturesDemo As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkPdfInvoices control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkPdfInvoices As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkConvertMultipleUrls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkConvertMultipleUrls As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkHtmlInHeaderAndFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkHtmlInHeaderAndFooter As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkHtmlElementsLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkHtmlElementsLocation As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkRepeatTableHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkRepeatTableHead As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkTableOfContents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkTableOfContents As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkPdfSecurity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkPdfSecurity As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkAppendPdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkAppendPdf As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkHtmlToPdfElement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkHtmlToPdfElement As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkTextAndFonts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkTextAndFonts As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkImageElement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkImageElement As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkPdfShapes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkPdfShapes As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkPdfStamps control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkPdfStamps As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkSvgToPdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkSvgToPdf As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
