'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EvoHtmlToPdfWebDemo


	''' <summary>
	''' PdfShapes class.
	''' </summary>
	''' <remarks>
	''' Auto-generated class.
	''' </remarks>
	Partial Public Class PdfShapes

		''' <summary>
		''' ctrlDemoLinksBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ctrlDemoLinksBox As Global.EvoHtmlToPdfWebDemo.DemoLinksBox

		''' <summary>
		''' btnCreatePDF control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnCreatePDF As Global.System.Web.UI.WebControls.Button
	End Class
End Namespace
